name: "SXM CDK Synth Action"
description: "action to wrap up NPM/CDK/"

inputs:
  APP: 
    description: "sxm-cdk-synth-test" # Replace with the name of your java app
    required: false
  GHE_OIDC_ROLE: 
    description: "GHE OIDC role"
    required: false
  AWS_REGION:
    description: "AWS Region"
    required: false
    default: "us-east-1" # Leave as is
  IMAGE_TAG: 
    description: "Image Tag"
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'

    - name: Install dependencies Including Ansible
        run: |
          python -m pip install --upgrade pip
          if [ -f skynet/requirements.txt ]; then pip install -r skynet/requirements.txt; fi
    